Reto 1: Exploracion inicial de los datos

1. Revisión inicial: examina los ficheros proporcionados y la documentación asociada a cada uno de ellos. Asegúrate de comprender el contexto de los datos y sus características principales antes de comenzar con la exploración. Comprueba que la estructura y el formato sean adecuados para su manipulación.
a. Utiliza herramientas como Python (pandas) para explorar y analizar la calidad de los datos antes de su carga en MongoDB.

In [17]:
import os
import pandas as pd
import csv

# Check if file exists first
excel_file_ae = 'doc_files/csv_files_raw/actividadeconomica202312.csv'
print(os.path.exists(excel_file_ae))  # Should print True
print(os.getcwd())                 # Shows your current working directory

True
/Users/ivonney.mendoza/repos/Master_UCM_II/5_Documentación bases de datos no sql-20260115/Actividad

In [18]:
# Ver las primeras 3 líneas crudas (sin parsear)
with open(excel_file_ae, encoding='utf-8-sig') as f:
    for i, line in enumerate(f):
        print(repr(line))
        if i == 2: break

'id_local;id_distrito_local;desc_distrito_local;id_barrio_local;desc_barrio_local;cod_barrio_local;id_seccion_censal_local;desc_seccion_censal_local;coordenada_x_local;coordenada_y_local;id_tipo_acceso_local;desc_tipo_acceso_local;id_situacion_local;desc_situacion_local;id_vial_edificio;clase_vial_edificio;desc_vial_edificio;id_ndp_edificio;id_clase_ndp_edificio;nom_edificio;num_edificio;cal_edificio;secuencial_local_PC;id_vial_acceso;clase_vial_acceso;desc_vial_acceso;id_ndp_acceso;id_clase_ndp_acceso;nom_acceso;num_acceso;cal_acceso;coordenada_x_agrupacion;coordenada_y_agrupacion;id_agrupacion;nombre_agrupacion;id_tipo_agrup;desc_tipo_agrup;id_planta_agrupado;id_local_agrupado;rotulo;id_seccion;desc_seccion;id_division;desc_division;id_epigrafe;desc_epigrafe;fx_carga;fx_datos_ini;fx_datos_fin\n'
'"270574777";20;"SAN BLAS-CANILLEJAS ";2004;"ARCOS               ";4;20044;44;0.0;0.0;12;"PC Asociado";1;"Abierto";67900;"CALLE                   ";"ARCOS DE JALON                                    ";"31026116";1;"NUM";34;"  ";10;67900;"CALLE                   ";"ARCOS DE JALON                                    ";"31026116";1;"NUM";34;"  ";;;"-1";"SIN AGRUPACION";-1;"SIN AGRUPACION";"PB";"";"CAMPAMENTO DE VERANO CEIP MARIA MOLINER";"P";"EDUCACIÓN";"85";"EDUCACIÓN";"855002";"ENSEÑANZA NO REGLADA (DEPORTIVA Y RECREATIVA, CULTURAL, CLASES DE RECUPERACION, INFORMATICA)";"2023-12-08 07:00:45.89";"2023-12-01";"2023-12-01"\n'
'"270574779";20;"SAN BLAS-CANILLEJAS ";2004;"ARCOS               ";4;20044;44;0.0;0.0;12;"PC Asociado";1;"Abierto";67900;"CALLE                   ";"ARCOS DE JALON                                    ";"31024172";1;"NUM";22;"  ";10;67900;"CALLE                   ";"ARCOS DE JALON                                    ";"31024172";1;"NUM";22;"  ";;;"-1";"SIN AGRUPACION";-1;"SIN AGRUPACION";"PB";"";"CAMPAMENTO VERANO CEE FUNDACION GOYENECHE";"P";"EDUCACIÓN";"85";"EDUCACIÓN";"855002";"ENSEÑANZA NO REGLADA (DEPORTIVA Y RECREATIVA, CULTURAL, CLASES DE RECUPERACION, INFORMATICA)";"2023-12-08 07:00:45.89";"2023-12-01";"2023-12-01"\n'

In [19]:
# Revisar delimitador actividad economica
with open(excel_file_ae, encoding='utf-8-sig') as f:
    dialect = csv.Sniffer().sniff(f.read(2048))
    print('Delimitador detectado:', repr(dialect.delimiter))

Delimitador detectado: ';'

In [20]:
# Abrir archivo licencias y revisar el delimitador
excel_file_lic = 'doc_files/csv_files_raw/licencias202312.csv'
with open(excel_file_lic, encoding='utf-8-sig') as f:
    dialect = csv.Sniffer().sniff(f.read(2048))
    print('Delimitador detectado:', repr(dialect.delimiter))

Delimitador detectado: ';'

In [21]:
# Abrir archivo locales y revisar el delimitador
excel_file_loc = 'doc_files/csv_files_raw/locales202312.csv'
with open(excel_file_loc, encoding='utf-8-sig') as f:
    dialect = csv.Sniffer().sniff(f.read(2048))
    print('Delimitador detectado:', repr(dialect.delimiter))

Delimitador detectado: ';'

In [23]:
# Abrir archivo terrazas y revisar el delimitador
excel_file_terr = 'doc_files/csv_files_raw/terrazas202312.csv'
with open(excel_file_terr, encoding='utf-8-sig') as f:
    dialect = csv.Sniffer().sniff(f.read(2048))
    print('Delimitador detectado:', repr(dialect.delimiter))

Delimitador detectado: ';'

In [24]:
# Exploracion inicial para actividad economica
with open(excel_file_ae, encoding='latin-1') as f:
    lines = f.readlines()

print(lines[0])    # Header

ï»¿id_local;id_distrito_local;desc_distrito_local;id_barrio_local;desc_barrio_local;cod_barrio_local;id_seccion_censal_local;desc_seccion_censal_local;coordenada_x_local;coordenada_y_local;id_tipo_acceso_local;desc_tipo_acceso_local;id_situacion_local;desc_situacion_local;id_vial_edificio;clase_vial_edificio;desc_vial_edificio;id_ndp_edificio;id_clase_ndp_edificio;nom_edificio;num_edificio;cal_edificio;secuencial_local_PC;id_vial_acceso;clase_vial_acceso;desc_vial_acceso;id_ndp_acceso;id_clase_ndp_acceso;nom_acceso;num_acceso;cal_acceso;coordenada_x_agrupacion;coordenada_y_agrupacion;id_agrupacion;nombre_agrupacion;id_tipo_agrup;desc_tipo_agrup;id_planta_agrupado;id_local_agrupado;rotulo;id_seccion;desc_seccion;id_division;desc_division;id_epigrafe;desc_epigrafe;fx_carga;fx_datos_ini;fx_datos_fin

In [25]:
# Exploracion inicial para licencias
with open(excel_file_lic, encoding='latin-1') as f:
    lines = f.readlines()

print(lines[0])    # Header

ï»¿id_local;id_distrito_local;desc_distrito_local;id_barrio_local;desc_barrio_local;cod_barrio_local;id_seccion_censal_local;desc_seccion_censal_local;coordenada_x_local;coordenada_y_local;id_tipo_acceso_local;desc_tipo_acceso_local;id_situacion_local;desc_situacion_local;id_ndp_edificio;id_clase_ndp_edificio;id_vial_edificio;clase_vial_edificio;desc_vial_edificio;nom_edificio;num_edificio;cal_edificio;secuencial_local_PC;id_ndp_acceso;id_clase_ndp_acceso;id_vial_acceso;clase_vial_acceso;desc_vial_acceso;nom_acceso;num_acceso;cal_acceso;coordenada_x_agrupacion;coordenada_y_agrupacion;id_agrupacion;nombre_agrupacion;id_tipo_agrup;desc_tipo_agrup;id_planta_agrupado;id_local_agrupado;rotulo;ref_licencia;id_tipo_licencia;desc_tipo_licencia;id_tipo_situacion_licencia;desc_tipo_situacion_licencia;Fecha_Dec_Lic;fx_carga;fx_datos_ini;fx_datos_fin

In [26]:
# Exploracion inicial para locales
with open(excel_file_loc, encoding='latin-1') as f:
    lines = f.readlines()

print(lines[0])    # Header

ï»¿id_local;id_distrito_local;desc_distrito_local;id_barrio_local;desc_barrio_local;cod_barrio_local;id_seccion_censal_local;desc_seccion_censal_local;coordenada_x_local;coordenada_y_local;id_tipo_acceso_local;desc_tipo_acceso_local;id_situacion_local;desc_situacion_local;id_vial_edificio;clase_vial_edificio;desc_vial_edificio;id_ndp_edificio;id_clase_ndp_edificio;nom_edificio;num_edificio;cal_edificio;secuencial_local_PC;id_vial_acceso;clase_vial_acceso;desc_vial_acceso;id_ndp_acceso;id_clase_ndp_acceso;nom_acceso;num_acceso;cal_acceso;coordenada_x_agrupacion;coordenada_y_agrupacion;id_agrupacion;nombre_agrupacion;id_tipo_agrup;desc_tipo_agrup;id_planta_agrupado;id_local_agrupado;rotulo;cod_postal;hora_apertura1;hora_apertura2;hora_cierre1;hora_cierre2;fx_carga;fx_datos_ini;fx_datos_fin

In [27]:
# Exploracion inicial para terrazas
with open(excel_file_terr, encoding='latin-1') as f:
    lines = f.readlines()

print(lines[0])    # Header

ï»¿id_terraza;id_local;id_distrito_local;desc_distrito_local;id_barrio_local;desc_barrio_local;id_ndp_edificio;id_clase_ndp_edificio;id_vial_edificio;clase_vial_edificio;desc_vial_edificio;nom_edificio;num_edificio;Cod_Postal;coordenada_x_local;coordenada_y_local;id_tipo_acceso_local;desc_tipo_acceso_local;id_situacion_local;desc_situacion_local;secuencial_local_PC;Escalera;id_planta_agrupado;id_local_agrupado;coordenada_x_agrupacion;coordenada_y_agrupacion;rotulo;id_periodo_terraza;desc_periodo_terraza;id_situacion_terraza;desc_situacion_terraza;Superficie_ES;Superficie_RA;Fecha_confir_ult_decreto_resol;id_ndp_terraza;id_clase_ndp_terraza;id_vial;desc_clase;desc_nombre;nom_terraza;num_terraza;cal_terraza;desc_ubicacion_terraza;hora_ini_LJ_es;hora_fin_LJ_es;hora_ini_LJ_ra;hora_fin_LJ_ra;hora_ini_VS_es;hora_fin_VS_es;hora_ini_VS_ra;hora_fin_VS_ra;mesas_aux_es;mesas_aux_ra;mesas_es;mesas_ra;sillas_es;sillas_ra;cal_edificio;fx_carga;fx_datos_ini;fx_datos_fin

In [28]:
ae = pd.read_csv(
    excel_file_ae,
    sep=';',
    encoding='utf-8-sig',
    low_memory=False       
)
ae.head(2)

,id_local,id_distrito_local,desc_distrito_local,id_barrio_local,desc_barrio_local,cod_barrio_local,id_seccion_censal_local,desc_seccion_censal_local,coordenada_x_local,coordenada_y_local,...,rotulo,id_seccion,desc_seccion,id_division,desc_division,id_epigrafe,desc_epigrafe,fx_carga,fx_datos_ini,fx_datos_fin
0,270574777,20,SAN BLAS-CANILLEJAS,2004,ARCOS,4,20044,44,0.0,0.0,...,CAMPAMENTO DE VERANO CEIP MARIA MOLINER,P,EDUCACIÓN,85,EDUCACIÓN,855002,"ENSEÑANZA NO REGLADA (DEPORTIVA Y RECREATIVA, ...",2023-12-08 07:00:45.89,2023-12-01,2023-12-01
1,270574779,20,SAN BLAS-CANILLEJAS,2004,ARCOS,4,20044,44,0.0,0.0,...,CAMPAMENTO VERANO CEE FUNDACION GOYENECHE,P,EDUCACIÓN,85,EDUCACIÓN,855002,"ENSEÑANZA NO REGLADA (DEPORTIVA Y RECREATIVA, ...",2023-12-08 07:00:45.89,2023-12-01,2023-12-01

In [29]:
lic = pd.read_csv(
    excel_file_lic,
    sep=';',
    encoding='utf-8-sig',
    low_memory=False        # Reads full file before inferring types
)
lic.head(2)

,id_local,id_distrito_local,desc_distrito_local,id_barrio_local,desc_barrio_local,cod_barrio_local,id_seccion_censal_local,desc_seccion_censal_local,coordenada_x_local,coordenada_y_local,...,rotulo,ref_licencia,id_tipo_licencia,desc_tipo_licencia,id_tipo_situacion_licencia,desc_tipo_situacion_licencia,Fecha_Dec_Lic,fx_carga,fx_datos_ini,fx_datos_fin
0,270366725,7,CHAMBERI,704,ALMAGRO,4,7092,92,441214.60,4476496.5,...,CAFE PLATINA ...,350/2023/26343,4,Transmisión de licencia Urbanística,5,Transmisión de Licencia Concedida,01/01/1900,2023-12-08 07:00:33.407,2023-12-01,2023-12-01
1,270433440,8,FUENCARRAL-EL PARDO,804,EL PILAR,4,8078,78,440308.62,4481076.5,...,CLINICA VETERINARIA GINZO DE LIMIA,108/2007/07166,2,Licencia Urbanística,2,Concedida,31/08/2009,2023-12-08 07:00:33.407,2023-12-01,2023-12-01

In [30]:
loc = pd.read_csv(
    excel_file_loc,
    sep=';',
    encoding='utf-8-sig',
    low_memory=False        # Reads full file before inferring types
)
loc.head(2)

,id_local,id_distrito_local,desc_distrito_local,id_barrio_local,desc_barrio_local,cod_barrio_local,id_seccion_censal_local,desc_seccion_censal_local,coordenada_x_local,coordenada_y_local,...,id_local_agrupado,rotulo,cod_postal,hora_apertura1,hora_apertura2,hora_cierre1,hora_cierre2,fx_carga,fx_datos_ini,fx_datos_fin
0,20000596,2,ARGANZUELA,203,CHOPERA,3,2043,43,440788.6,4471857.5,...,D1,LA CAÑA,28045,09:00,NaN,NaN,22:00,2023-12-08 07:01:00.047,2023-12-01,2023-12-01
1,20000605,2,ARGANZUELA,201,IMPERIAL,1,2107,107,439316.6,4472540.5,...,01,CAFETERIA PIRAMIDES,28005,NaN,NaN,NaN,NaN,2023-12-08 07:01:00.047,2023-12-01,2023-12-01

In [31]:
terr = pd.read_csv(
    excel_file_terr,
    sep=';',
    encoding='utf-8-sig',
    low_memory=False        # Reads full file before inferring types
)
loc.head(2)

,id_local,id_distrito_local,desc_distrito_local,id_barrio_local,desc_barrio_local,cod_barrio_local,id_seccion_censal_local,desc_seccion_censal_local,coordenada_x_local,coordenada_y_local,...,id_local_agrupado,rotulo,cod_postal,hora_apertura1,hora_apertura2,hora_cierre1,hora_cierre2,fx_carga,fx_datos_ini,fx_datos_fin
0,20000596,2,ARGANZUELA,203,CHOPERA,3,2043,43,440788.6,4471857.5,...,D1,LA CAÑA,28045,09:00,NaN,NaN,22:00,2023-12-08 07:01:00.047,2023-12-01,2023-12-01
1,20000605,2,ARGANZUELA,201,IMPERIAL,1,2107,107,439316.6,4472540.5,...,01,CAFETERIA PIRAMIDES,28005,NaN,NaN,NaN,NaN,2023-12-08 07:01:00.047,2023-12-01,2023-12-01

2. Revisión de campos: analiza los campos de cada fichero, identificando su contenido, tipos de datos y posibles inconsistencias. Evalúa la calidad de los datos, buscando errores comunes como valores nulos, duplicados o inconsistencias en los formatos.
a. No tienes que realizar una revisión profunda y tampoco limpiar los datos en su totalidad, basta con comprobar algunos documentos de muestra.

In [32]:
print('Shape:', ae.shape)
print('Duplicados:', ae.duplicated().sum())

# Tipos de datos — formato tabla vertical
print('\nTipos de datos:')
print(pd.DataFrame({
    'columna': ae.columns,
    'dtype':   ae.dtypes.values,
    'nulos':   ae.isnull().sum().values,
    'nulos_%': (ae.isnull().mean() * 100).round(1).values
}).to_string(index=False))

Shape: (169559, 49)
Duplicados: 0

Tipos de datos:
                  columna   dtype  nulos  nulos_%
                 id_local   int64      0      0.0
        id_distrito_local   int64      0      0.0
      desc_distrito_local  object      0      0.0
          id_barrio_local   int64      0      0.0
        desc_barrio_local  object      0      0.0
         cod_barrio_local   int64      0      0.0
  id_seccion_censal_local   int64      0      0.0
desc_seccion_censal_local   int64      0      0.0
       coordenada_x_local float64      0      0.0
       coordenada_y_local float64      0      0.0
     id_tipo_acceso_local   int64      0      0.0
   desc_tipo_acceso_local  object      0      0.0
       id_situacion_local   int64      0      0.0
     desc_situacion_local  object      0      0.0
         id_vial_edificio   int64      0      0.0
      clase_vial_edificio  object      0      0.0
       desc_vial_edificio  object      0      0.0
          id_ndp_edificio   int64      0      0.0
    id_clase_ndp_edificio   int64      0      0.0
             nom_edificio  object      0      0.0
             num_edificio   int64      0      0.0
             cal_edificio  object      0      0.0
      secuencial_local_PC   int64      0      0.0
           id_vial_acceso   int64      0      0.0
        clase_vial_acceso  object      0      0.0
         desc_vial_acceso  object      0      0.0
            id_ndp_acceso   int64      0      0.0
      id_clase_ndp_acceso   int64      0      0.0
               nom_acceso  object      0      0.0
               num_acceso   int64      0      0.0
               cal_acceso  object      0      0.0
  coordenada_x_agrupacion float64 153427     90.5
  coordenada_y_agrupacion float64 153427     90.5
            id_agrupacion   int64      0      0.0
        nombre_agrupacion  object      0      0.0
            id_tipo_agrup   int64      0      0.0
          desc_tipo_agrup  object      0      0.0
       id_planta_agrupado  object   1869      1.1
        id_local_agrupado  object  64940     38.3
                   rotulo  object      0      0.0
               id_seccion  object      0      0.0
             desc_seccion  object      0      0.0
              id_division  object      0      0.0
            desc_division  object      0      0.0
              id_epigrafe  object      0      0.0
            desc_epigrafe  object      0      0.0
                 fx_carga  object      0      0.0
             fx_datos_ini  object      0      0.0
             fx_datos_fin  object      0      0.0

In [33]:
print('Shape:', lic.shape)
print('Duplicados:', lic.duplicated().sum())

# Tipos de datos — formato tabla vertical
print('\nTipos de datos:')
print(pd.DataFrame({
    'columna': lic.columns,
    'dtype':   lic.dtypes.values,
    'nulos':   lic.isnull().sum().values,
    'nulos_%': (lic.isnull().mean() * 100).round(1).values
}).to_string(index=False))

Shape: (150829, 49)
Duplicados: 0

Tipos de datos:
                     columna   dtype  nulos  nulos_%
                    id_local   int64      0      0.0
           id_distrito_local   int64      0      0.0
         desc_distrito_local  object      0      0.0
             id_barrio_local   int64      0      0.0
           desc_barrio_local  object      0      0.0
            cod_barrio_local   int64      0      0.0
     id_seccion_censal_local   int64      0      0.0
   desc_seccion_censal_local   int64      0      0.0
          coordenada_x_local float64      0      0.0
          coordenada_y_local float64      0      0.0
        id_tipo_acceso_local   int64      0      0.0
      desc_tipo_acceso_local  object      0      0.0
          id_situacion_local   int64      0      0.0
        desc_situacion_local  object      0      0.0
             id_ndp_edificio   int64      0      0.0
       id_clase_ndp_edificio   int64      0      0.0
            id_vial_edificio   int64      0      0.0
         clase_vial_edificio  object      0      0.0
          desc_vial_edificio  object      0      0.0
                nom_edificio  object      0      0.0
                num_edificio   int64      0      0.0
                cal_edificio  object      0      0.0
         secuencial_local_PC   int64      0      0.0
               id_ndp_acceso   int64      0      0.0
         id_clase_ndp_acceso   int64      0      0.0
              id_vial_acceso   int64      0      0.0
           clase_vial_acceso  object      0      0.0
            desc_vial_acceso  object      0      0.0
                  nom_acceso  object      0      0.0
                  num_acceso   int64      0      0.0
                  cal_acceso  object      0      0.0
     coordenada_x_agrupacion float64 141556     93.9
     coordenada_y_agrupacion float64 141556     93.9
               id_agrupacion   int64      0      0.0
           nombre_agrupacion  object      0      0.0
               id_tipo_agrup   int64      0      0.0
             desc_tipo_agrup  object      0      0.0
          id_planta_agrupado  object    207      0.1
           id_local_agrupado  object  35079     23.3
                      rotulo  object      0      0.0
                ref_licencia  object      0      0.0
            id_tipo_licencia   int64      0      0.0
          desc_tipo_licencia  object      0      0.0
  id_tipo_situacion_licencia   int64      0      0.0
desc_tipo_situacion_licencia  object      0      0.0
               Fecha_Dec_Lic  object      0      0.0
                    fx_carga  object      0      0.0
                fx_datos_ini  object      0      0.0
                fx_datos_fin  object      0      0.0

In [34]:
print('Shape:', loc.shape)
print('Duplicados:', loc.duplicated().sum())

# Tipos de datos — formato tabla vertical
print('\nTipos de datos:')
print(pd.DataFrame({
    'columna': loc.columns,
    'dtype':   loc.dtypes.values,
    'nulos':   loc.isnull().sum().values,
    'nulos_%': (loc.isnull().mean() * 100).round(1).values
}).to_string(index=False))

Shape: (151162, 48)
Duplicados: 0

Tipos de datos:
                  columna   dtype  nulos  nulos_%
                 id_local   int64      0      0.0
        id_distrito_local   int64      0      0.0
      desc_distrito_local  object      0      0.0
          id_barrio_local   int64      0      0.0
        desc_barrio_local  object      0      0.0
         cod_barrio_local   int64      0      0.0
  id_seccion_censal_local   int64      0      0.0
desc_seccion_censal_local   int64      0      0.0
       coordenada_x_local float64      0      0.0
       coordenada_y_local float64      0      0.0
     id_tipo_acceso_local   int64      0      0.0
   desc_tipo_acceso_local  object      0      0.0
       id_situacion_local   int64      0      0.0
     desc_situacion_local  object      0      0.0
         id_vial_edificio   int64      0      0.0
      clase_vial_edificio  object      0      0.0
       desc_vial_edificio  object      0      0.0
          id_ndp_edificio   int64      0      0.0
    id_clase_ndp_edificio   int64      0      0.0
             nom_edificio  object      0      0.0
             num_edificio   int64      0      0.0
             cal_edificio  object      0      0.0
      secuencial_local_PC   int64      0      0.0
           id_vial_acceso   int64      0      0.0
        clase_vial_acceso  object      0      0.0
         desc_vial_acceso  object      0      0.0
            id_ndp_acceso   int64      0      0.0
      id_clase_ndp_acceso   int64      0      0.0
               nom_acceso  object      0      0.0
               num_acceso   int64      0      0.0
               cal_acceso  object      0      0.0
  coordenada_x_agrupacion float64 136661     90.4
  coordenada_y_agrupacion float64 136661     90.4
            id_agrupacion   int64      0      0.0
        nombre_agrupacion  object      0      0.0
            id_tipo_agrup   int64      0      0.0
          desc_tipo_agrup  object      0      0.0
       id_planta_agrupado  object   1648      1.1
        id_local_agrupado  object  60717     40.2
                   rotulo  object      0      0.0
               cod_postal   int64      0      0.0
           hora_apertura1  object 142366     94.2
           hora_apertura2  object 150350     99.5
             hora_cierre1  object 144851     95.8
             hora_cierre2  object 150300     99.4
                 fx_carga  object      0      0.0
             fx_datos_ini  object      0      0.0
             fx_datos_fin  object      0      0.0

In [35]:
print('Shape:', terr.shape)
print('Duplicados:', terr.duplicated().sum())

# Tipos de datos — formato tabla vertical
print('\nTipos de datos:')
print(pd.DataFrame({
    'columna': terr.columns,
    'dtype':   terr.dtypes.values,
    'nulos':   terr.isnull().sum().values,
    'nulos_%': (terr.isnull().mean() * 100).round(1).values
}).to_string(index=False))

Shape: (6788, 61)
Duplicados: 0

Tipos de datos:
                       columna   dtype  nulos  nulos_%
                    id_terraza   int64      0      0.0
                      id_local   int64      0      0.0
             id_distrito_local   int64      0      0.0
           desc_distrito_local  object      0      0.0
               id_barrio_local   int64      0      0.0
             desc_barrio_local  object      0      0.0
               id_ndp_edificio   int64      0      0.0
         id_clase_ndp_edificio   int64      0      0.0
              id_vial_edificio   int64      0      0.0
           clase_vial_edificio  object      0      0.0
            desc_vial_edificio  object      0      0.0
                  nom_edificio  object      0      0.0
                  num_edificio   int64      0      0.0
                    Cod_Postal   int64      0      0.0
            coordenada_x_local float64      0      0.0
            coordenada_y_local float64      0      0.0
          id_tipo_acceso_local   int64      0      0.0
        desc_tipo_acceso_local  object      0      0.0
            id_situacion_local   int64      0      0.0
          desc_situacion_local  object      0      0.0
           secuencial_local_PC   int64      0      0.0
                      Escalera  object   6665     98.2
            id_planta_agrupado  object      4      0.1
             id_local_agrupado  object   1264     18.6
       coordenada_x_agrupacion float64   6683     98.5
       coordenada_y_agrupacion float64   6683     98.5
                        rotulo  object      0      0.0
            id_periodo_terraza   int64      0      0.0
          desc_periodo_terraza  object      0      0.0
          id_situacion_terraza   int64      0      0.0
        desc_situacion_terraza  object      0      0.0
                 Superficie_ES float64      0      0.0
                 Superficie_RA float64   1178     17.4
Fecha_confir_ult_decreto_resol  object      0      0.0
                id_ndp_terraza   int64      0      0.0
          id_clase_ndp_terraza   int64      0      0.0
                       id_vial   int64      0      0.0
                    desc_clase  object      0      0.0
                   desc_nombre  object      0      0.0
                   nom_terraza  object      0      0.0
                   num_terraza   int64      0      0.0
                   cal_terraza  object      0      0.0
        desc_ubicacion_terraza  object      0      0.0
                hora_ini_LJ_es  object      0      0.0
                hora_fin_LJ_es  object      0      0.0
                hora_ini_LJ_ra  object   1178     17.4
                hora_fin_LJ_ra  object   1178     17.4
                hora_ini_VS_es  object      0      0.0
                hora_fin_VS_es  object      0      0.0
                hora_ini_VS_ra  object   1178     17.4
                hora_fin_VS_ra  object   1178     17.4
                  mesas_aux_es   int64      0      0.0
                  mesas_aux_ra float64    239      3.5
                      mesas_es   int64      0      0.0
                      mesas_ra float64    239      3.5
                     sillas_es   int64      0      0.0
                     sillas_ra float64    239      3.5
                  cal_edificio  object      0      0.0
                      fx_carga  object      0      0.0
                  fx_datos_ini  object      0      0.0
                  fx_datos_fin  object      0      0.0

In [37]:
cols1 = set(ae.columns)
cols2 = set(lic.columns)
cols3 = set(loc.columns)
cols4 = set(terr.columns)

# Entre los 3
comunes_4 = cols1 & cols2 & cols3 & cols4
print('Comunes en los 4:', comunes_4)

Comunes en los 4: {'rotulo', 'desc_barrio_local', 'coordenada_x_local', 'secuencial_local_PC', 'id_local_agrupado', 'id_distrito_local', 'fx_carga', 'coordenada_x_agrupacion', 'id_vial_edificio', 'desc_distrito_local', 'id_planta_agrupado', 'desc_situacion_local', 'num_edificio', 'id_situacion_local', 'coordenada_y_local', 'desc_vial_edificio', 'id_ndp_edificio', 'fx_datos_fin', 'id_local', 'coordenada_y_agrupacion', 'id_tipo_acceso_local', 'clase_vial_edificio', 'fx_datos_ini', 'desc_tipo_acceso_local', 'id_clase_ndp_edificio', 'cal_edificio', 'nom_edificio', 'id_barrio_local'}

De acuerdo a los datos explorados existe un conjunto de campos que son comunes a los cuatro datasets que pueden ser utiles para el ejercicio, en especial id_local o los relatvos a la

In [39]:
print('Distritos únicos:', ae['id_distrito_local'].nunique())
print(ae[['id_distrito_local', 'desc_distrito_local']].drop_duplicates().sort_values('id_distrito_local'))

print('\nBarrios únicos:', ae['id_barrio_local'].nunique())

Distritos únicos: 21
     id_distrito_local   desc_distrito_local
13                   1  CENTRO
7                    2  ARGANZUELA
80                   3  RETIRO
40                   4  SALAMANCA
96                   5  CHAMARTIN
8                    6  TETUAN
16                   7  CHAMBERI
6                    8  FUENCARRAL-EL PARDO
32                   9  MONCLOA-ARAVACA
21                  10  LATINA
2                   11  CARABANCHEL
9                   12  USERA
35                  13  PUENTE DE VALLECAS
161                 14  MORATALAZ
44                  15  CIUDAD LINEAL
3                   16  HORTALEZA
12                  17  VILLAVERDE
18                  18  VILLA DE VALLECAS
30                  19  VICALVARO
0                   20  SAN BLAS-CANILLEJAS
131                 21  BARAJAS

Barrios únicos: 131